
version: '3.8'

services:
  app:
    build:
      context: .
    container_name: money-flow-guardian-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - POSTGRES_ENABLED=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - API_PORT=8080
    volumes:
      - ./data:/data
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    external: true
