
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: money-flow-guardian-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - POSTGRES_ENABLED=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - API_PORT=8081
      - FMP_API_KEY=wBPziir7XFSKm4WIZpLGx6nyF5TmN4XC
      - ALPHA_VANTAGE_API_KEY=LR78N65XUDF2EZDB
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    external: true
